datadir = 'data'
resourcedir = 'resources'

[[assets]]
name = 'dbpedia_t2ksubset' # 
class = 'RDFSearcher'
labelProperties = ['http://dbpedia.org/ontology/title']
store = {class = 'Trident', configuration = 'data/kb/dbpedia_t2ksubset/db/'}

[[assets]]
name = 'dbpedia_2014_part2'
class = 'RDFSearcher'
labelProperties = ['http://dbpedia.org/ontology/title']
store = {class = 'Trident', configuration = 'data/kb/dbpedia/2014_part2/'}

[[assets]]
name = 'dbpedia_2016'
class = 'RDFSearcher'
labelProperties = ['http://dbpedia.org/ontology/title']
store = {class = 'Trident', configuration = 'data/kb/dbpedia/2016-10/'}

[[assets]]
name = 'dbpedia_t2ksubset_es'
class = 'ElasticSearcher'
index = 'dbpediasub-6'
baseuri = 'http://dbpedia.org/resource/'
es_kwargs.hosts = ['bricks07']
prop_uri.type = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
prop_baseuri.type = 'http://dbpedia.org/ontology/'



[[assets]]
name = 'dbpedia_t2ksubset_extralabels'
class = 'SQLiteSearcher'
files = 'data/dbpedia-t2ksubset-label-sqlitedbs/*'
baseuri = 'http://dbpedia.org/resource/'
    [assets.graph]
    class = 'RDFSearcher'
    labelProperties = ['http://dbpedia.org/ontology/title']
    store = {class = 'Trident', configuration = 'data/kb/dbpedia_t2ksubset/db+extralabels/'}

[[assets]]
name = 'dbpedialookup_t2ksubset'
class = 'SQLiteSearcher'
files = 'data/dbpedia-lookup-sqlitedbs/*'
baseuri = 'http://dbpedia.org/resource/'
fallback = {class = 'DBpediaLookup'}
    [assets.graph]
    name = 'dbpedia_t2ksubset'
    class = 'RDFSearcher'
    labelProperties = ['http://dbpedia.org/ontology/title']
    store = {class = 'Trident', configuration = 'data/kb/dbpedia_t2ksubset/db/'}


[[assets]]
name = 't2d-v1'
class = 'T2D'
download = [
    'http://webdatacommons.org/webtables/tables_instance.tar.gz',
    'http://webdatacommons.org/webtables/entities_instance.tar.gz',
    'http://webdatacommons.org/webtables/classes_instance.csv',
    'http://webdatacommons.org/webtables/attributes_instance.tar.gz',
]
version = 1
fixuri = 't2d_fix.csv'

[[assets]]
name = 't2d-v2'
class = 'T2D'
download = [
    'http://webdatacommons.org/webtables/extended_instance_goldstandard.tar.gz',
]
version = 2
fixuri = 't2d_fix.csv'
