datadir = "data"
resourcedir = "resources"

## Executors ##

[[assets]]
name = "dask-local"
class = "DaskHashBag"
scheduler_port = 8786
dashboard_address = ":8787"
n_workers = 4
threads_per_worker = 1

[[assets]]
name = "dask-local-big"
class = "DaskHashBag"
scheduler_port = 8786
dashboard_address = ":8787"
n_workers = 8
threads_per_worker = 4

[[assets]]
name = "dask-cluster"
class = "DaskHashBag"
address = "tcp://192.168.62.207:8786"


## Knowledge Bases ##

[[assets]]
name = "wikidata-20200709-direct-prefLabel-en"
class = "RDFSearcher"
typeProperties = ["http://www.wikidata.org/prop/direct/P31"]
    [assets.store]
    class = "Trident"
    configuration = "../kb/wikidata/wikidata-20200709-direct-prefLabel-en-db/"

[[assets]]
name = "wikidata2019-P31inf-wikibase-simple-qualifiers"
class = "RDFSearcher"
typeProperties = ["http://www.wikidata.org/prop/direct/P31"]
qualifierIDProperty = "http://www.wikidata.org/prop/direct/id"
#wikiProp = "http://www.wikidata.org/entity/wikipediaId"
    [assets.store]
    class = "Trident"
    configuration = "../kb/wikidata/wikidata2019-P31inf-wikibase-simple-qualifiers/"
    ent_baseuri = "http://www.wikidata.org/entity/"
    prop_baseuri = "http://www.wikidata.org/prop/direct/"
    ns = {skos = "http://www.w3.org/2004/02/skos/core#"}
    
[[assets]]
name = "wikidata-20200713-direct-skos"
class = "RDFSearcher"
encoding = "wikidata"
typeProperties = ["http://www.wikidata.org/prop/direct/P31"]
    [assets.store]
    class = "Trident"
    configuration = "/scratch/kruit/kb/wikidata/20200713-direct-skos/"

[[assets]]
name  = "wikidata-live"
class = "RDFSearcher"
typeProperties = ["http://www.wikidata.org/prop/direct/P31"]
    [assets.store]
    class = "SparqlStore"
    configuration = "https://query.wikidata.org/sparql"

[[assets]]
name  = "wikidata-hdt"
class = "RDFSearcher"
encoding = "wikidata"
typeProperties = ["http://www.wikidata.org/prop/direct/P31"]
    [assets.store]
    class = "HDTStore"
    path = "/var/scratch/bbkruit/wikidata20200309.hdt"
    
[[assets]]
name = 'wiki-sqlite'
class = 'SQLiteWikiLookup'
sqlite_kwargs = {timeout = 60.0}
sqlitedb = 'data/wdid_wpname.sqlitedb'
baseuri = 'http://www.wikidata.org/entity/'

[[assets]]
name = 'wikidata-elastic'
class = 'ElasticDB'
cache = true
es_kwargs.hosts = ['bricks07:9200']
index='test-wd-statements,test-wd-wikilookup'
baseuri='http://www.wikidata.org/entity/Q'
propbaseuri='http://www.wikidata.org/prop/direct/P'

[[assets]]
name = 'wikidata-cache'
class = "SQLiteDB"
sqlite_kwargs = {timeout = 60.0}
sqlitedb = 'data/wikidata-cache.sqlitedb'
baseuri='http://www.wikidata.org/entity/Q'
propbaseuri='http://www.wikidata.org/prop/direct/P'

[[assets]]
name = 'wiki-pickle'
class = 'PickleWikiLookup'
file = 'data/wdid_wpname.pickle'


[[assets]]
name  = "wikidata-cluster"
class = "RDFSearcher"
typeProperties = ["http://www.wikidata.org/prop/direct/P31"]
    [assets.store]
    class = "SparqlStore"
    configuration = "http://192.168.62.207:8811/sparql"