datadir = 'data'
resourcedir = 'resources'

## Executors ##

[[assets]]
name = 'dask-local'
class = 'DaskHashBag'
scheduler_port = 8586
dashboard_address = ':8587'
n_workers = 4
threads_per_worker = 1

[[assets]]
name = 'dask-local-big'
class = 'DaskHashBag'
scheduler_port = 8586
dashboard_address = ':8587'
n_workers = 8
threads_per_worker = 4

[[assets]]
name = 'dask-cluster'
class = 'DaskHashBag'
address = 'tcp://192.168.62.207:8786'

[[assets]]
name = 'dask-cluster-2'
class = 'DaskHashBag'
address = 'tcp://192.168.62.207:8686'

## Knowledge Bases ##

[[assets]]
name = 'wikidata-trident'
class = 'RDFSearcher'
encoding = 'wikidata'
typeProperties = ['http://www.wikidata.org/prop/direct/P31']
    [assets.store]
    class = 'Trident'
    configuration = 'data/wikidata.tridentdb'

[[assets]]
name  = 'wikidata-live'
class = 'RDFSearcher'
typeProperties = ['http://www.wikidata.org/prop/direct/P31']
    [assets.store]
    class = 'SparqlStore'
    configuration = 'https://query.wikidata.org/sparql'

[[assets]]
name  = 'wikidata-hdt'
class = 'RDFSearcher'
encoding = 'wikidata'
typeProperties = ['http://www.wikidata.org/prop/direct/P31']
    [assets.store]
    class = 'HDTStore'
    path = '/var/scratch/bbkruit/wikidata20200309.hdt'
    

[[assets]]
name = 'wiki-sqlite'
class = 'SQLiteLookup'
sqlite_kwargs = {timeout = 60.0}
sqlitedb = 'data/wdid_wpname.sqlitedb'
baseuri = 'http://www.wikidata.org/entity/Q'

[[assets]]
name = 'wikidata-elastic'
class = 'ElasticDB'
cache = true
es_kwargs.hosts = ['bricks07:9200']
index='test-wd-statements,test-wd-wikilookup'
baseuri='http://www.wikidata.org/entity/Q'
propbaseuri='http://www.wikidata.org/prop/direct/P'

[[assets]]
name = 'wikidata-cache'
class = 'SQLiteDB'
sqlite_kwargs = {timeout = 60.0}
sqlitedb = 'data/wikidata-cache.sqlitedb'
baseuri='http://www.wikidata.org/entity/Q'
propbaseuri='http://www.wikidata.org/prop/direct/P'
