name = 'chartedIn'
datadir = "output/chartedIn/"
workdir = "output/chartedIn/"
cache = true

[[step]]
step = "extract"
    [step.source.warc]
    globstrings = ["./data/wikipedia-2019-12-P2291/*-00000.warc.gz"]
    
    #[step.source.wiki]
    #pred = "http://www.wikidata.org/prop/direct/P2291"
    #localurlprefix = "http://localhost:8989/wikipedia_en_all_nopic_2019-12/A/"
    #encoding = "utf-8"
    #sample=10
    
[[step]]
step = "reshape"
split_compound_columns = true
load_user = false
unpivot_heuristics = [{class = "NumSuffix"}]

[[step]]
step = "cluster"
addcontext = ["pgTitle"]
headerunions = true

[[step]]
step = "link"
linker_config = {}
lookup_cells = true
lookup_config = {name = 'wiki-lookup'}
    
[[step]]
step = "coltypes"
    [step.typer_config]
    class = "EntityType"
    db = {name = "wikidata-20200709-direct-prefLabel-en"}
    type_prop = "http://www.wikidata.org/prop/direct/P31"
    supertype_prop = "http://www.wikidata.org/prop/direct/P279"
    cover_threshold = 0.333

[[step]]
step = "cluster"
addcontext = []
headerunions = false
use_match_cache = false
agg_func = '@mean(  @max(headjacc, @pow(headvec, 4)), @max(bodylsh, bodytype, @pow(bodyvec, 4) ) )'
agg_threshold = 0.95
edge_exp = 3
agg_threshold_col = 0.5
store_align_meta = ["_id", "tableHeaders", "tableData", "entities", "classes"]
    
    [[step.matchers]]
    name  = 'headjacc'
    class = 'CellJaccMatcher'
    source = 'head'
    tokenize = true
    
    [[step.matchers]]
    name  = 'headvec'
    class = 'EmbeddingMatcher'
    source = 'head'
    wordvec_fname = "./data/glove.6B/glove.6B.50d.txt"

    [[step.matchers]]
    name  = 'bodylsh'
    class = 'LSHMatcher'
    source = 'body'
    redis_dir = "./redis-5.0.5/src/"
    port = 63790
    threshold = 0.5
    
    [[step.matchers]]
    name  = 'bodyvec'
    class = 'EmbeddingMatcher'
    source = 'body'
    wordvec_fname = "./data/glove.6B/glove.6B.50d.txt"
    
    [[step.matchers]]
    name  = 'bodytype'
    class = 'TypeCosMatcher'

#[[step]]
#step = "integrate"
#pfd_threshold = 0.95
#searcher_config = {name = "wikidata-hdt"}
#searcher_config = {name = "wikidata2019-P31inf-wikibase-simple-qualifiers"}