name = 'semtab-r2'
executor = 'dask'

[[assets]]
name='dask'
class = 'DaskHashBag'
n_workers=8
threads_per_worker=2
memory_target_fraction = 0.85


[input_tables]
input = 'dataset'
params = {class = 'Semtab', name = 'semtab-r2'}
#sample = 1000

[[step]]
step = 'link'
usecols = 'entcols'
lookup_config = {}

    [step.linker]
    class = 'Salient'
    searcher = {resolve = 'wikidata-20200713-direct-skos', datematch = 'dateparser'}
    prop_cover = 0.1
    expand = true
    max_backlink = 250
    min_score = 0.75
    #limit = 10
    #only_majority = '@type'
    
        [step.linker_config.replace_class]
        'http://www.wikidata.org/entity/Q164509' = 'http://www.wikidata.org/entity/Q5'
    
        #[step.linker_config.exclude_about]
        #'http://www.wikidata.org/prop/direct/P31' = [
        #    'http://www.wikidata.org/entity/Q4167410'
        #]
