name = 't2d-v2-baseline'
datadir = 'data'
workdir = 'output/t2d-v2-baseline/'
cache = false

[input_tables]
input = 'dataset'
params = 't2d-v2'
#sample = 2

[[step]]
step = 'link'
#usecols = 'keycol'
usecols = 'non_numeric_cols'
#usecols = 'heuristic_key' # only works for literal props

lookup_config = {}
    [step.linker_config]
    class = 'Salient'
    graph = {resolve = 'dbpedia_t2ksubset'}
    prop_cover = 0.2
    class_cover = 0.2
    #only_majority = '@type'
    searcher = {resolve = 'dbpedia_t2ksubset_extralabels'}
    
    #[step.linker_config]
    #class = 'First'
    #    [step.linker_config.searcher]
    #    class = 'SQLiteSearcher'
    #    files = 'data/dbpedia-t2ksubset-label-sqlitedbs-2/*'
    #    baseuri = 'http://dbpedia.org/resource/'

[[step]]
step = 'score'
labels = 't2d-v2'
keycol_only = true
report = ['pdf', 'md']

[[step]]
step = 'triples'

[[step]]
step = 'novelty'
searcher_config = {resolve = 'dbpedia_t2ksubset'}