name = 't2d-v2-baseline'
datadir = 'data'
workdir = 'output/t2d-v2-baseline/'
cache = false

[input_tables]
input = 'dataset'
params = 't2d-v2'

[[step]]
    [[step.split]]
    step = 'link'
    #usecols = 'non_numeric_cols'
    usecols = 'heuristic_key' # only works for literal props
    lookup_config = {}
        [step.split.linker_config]
        class = 'Salient'
        graph = {resolve = 'dbpedia_t2ksubset'}
        prop_cover = 0.2
        class_cover = 0.2
        searcher = {resolve = 'dbpedia_t2ksubset_extralabels'}
    
    [[step.split]]
    step = 'link'
    #usecols = 'non_numeric_cols'
    usecols = 'heuristic_key' # only works for literal props
    lookup_config = {}
        [step.split.linker_config]
        class = 'First'
        searcher = {resolve = 'dbpedia_t2ksubset_extralabels'}


[[step]]
step = 'score'
labels = 't2d-v2'
keycol_only = true
report = ['pdf', 'md']

[[step]]
step = 'triples'

[[step]]
step = 'novelty'
searcher_config = {resolve = 'dbpedia_t2ksubset'}

[[step]]
step = 'report'
keycol_only = true