name = 't2d-v2-baseline'
datadir = 'data'
resourcedir = 'resources'
workdir = 'output/t2d-v2-baseline/'
cache = false

[[baseline]]
step = 'dataset'
dataset = {resolve = 't2d-v2'}

[[baseline]]
step = 'link'
usecols = 'keycol'
linker = {resolve = 'baseline_linker'}


[[step]]
step = 'dataset'
params = 't2d-v2'
#sample = 5

[[step]]
    [[step.split]]
    step = 'link'
    usecols = 'non_numeric_cols'
    #usecols = 'heuristic_key' # only works for literal props
    lookup_config = {}
        [step.split.linker_config]
        class = 'First'
        searcher = {resolve = 'dbpedia_t2ksubset_es'}

    [[step.split]]
    step = 'link'
    usecols = 'non_numeric_cols'
    #usecols = 'heuristic_key' # only works for literal props
    lookup_config = {}
        [step.split.linker_config]
        class = 'First'
        searcher = {resolve = 'dbpedia_t2ksubset_es'}
        contextual = true
        search_limit = 1
        majority_class = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
        majority_class_search = true

    [[step.split]]
    step = 'link'
    usecols = 'non_numeric_cols'
    #usecols = 'heuristic_key' # only works for literal props
    lookup_config = {}
        [step.split.linker_config]
        class = 'Salient'
        graph = {resolve = 'dbpedia_t2ksubset'}
        prop_cover = 0.2
        class_cover = 0.2
        searcher = {resolve = 'dbpedia_t2ksubset_es'}
    
    

[[step]]
step = 'score'
labels = 't2d-v2'
keycol_only = true

[[step]]
step = 'triples'

[[step]]
step = 'novelty'
searcher_config = {resolve = 'dbpedia_t2ksubset'}

[[step]]
step = 'report'
keycol_only = true
curve = true
