datadir = 'data'
resourcedir = 'resources'

[dbpedia_t2ksubset_es]
class = 'link.ElasticSearcher'
index = 'dbpediasub-7'
baseuri = 'http://dbpedia.org/resource/'
es_kwargs = {hosts = ['bricks07'], timeout = 60}
prop_uri = {type = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"}
prop_baseuri = {type = 'http://dbpedia.org/ontology/'}
propbaseuri = "http://dbpedia.org/ontology/"


[linker]
class = "link.First"
limit = 1
contextual = true
search_limit = 1
majority_class = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
majority_class_search = true
searcher = {resolve = 'dbpedia_t2ksubset_es'}


[[baseline]]
step = 'dataset'
dataset = {resolve = 't2d-v2'}

[[baseline]]
step = 'link'
usecols = 'keycol'
linker = {resolve = 'linker'}


[[step]]
step = 'dataset'
params = 't2d-v2'
#take = n

[[step]]
    [[step.split]]
    step = 'link'
    usecols = 'non_numeric_cols'
    #usecols = 'heuristic_key' # only works for literal props
    lookup_config = {}
        [step.split.linker_config]
        class = 'First'
        searcher = {resolve = 'dbpedia_t2ksubset_es'}

    [[step.split]]
    step = 'link'
    usecols = 'non_numeric_cols'
    #usecols = 'heuristic_key' # only works for literal props
    lookup_config = {}
        [step.split.linker_config]
        class = 'First'
        searcher = {resolve = 'dbpedia_t2ksubset_es'}
        contextual = true
        search_limit = 1
        majority_class = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
        majority_class_search = true

    [[step.split]]
    step = 'link'
    usecols = 'non_numeric_cols'
    #usecols = 'heuristic_key' # only works for literal props
    lookup_config = {}
        [step.split.linker_config]
        class = 'Salient'
        graph = {resolve = 'dbpedia_t2ksubset'}
        prop_cover = 0.2
        class_cover = 0.2
        searcher = {resolve = 'dbpedia_t2ksubset_es'}
    
    

[[step]]
step = 'score'
annotations = 't2d-v2'
keycol_only = true

[[step]]
step = 'triples'

[[step]]
step = 'novelty'
searcher_config = {resolve = 'dbpedia_t2ksubset'}

[[step]]
step = 'report'
keycol_only = true
curve = true
