name = "TabEL"
datadir = "data"

[[assets]]
name  = "tabel"
class = "Annotation"
download = [
    "http://websail-fe.cs.northwestern.edu/TabEL/tables.json.gz",
]
path = "data/TabEL"
fname = "tables.json.gz"

[[assets]]
name = 'lookup'
#resolve = 'wikidata-elastic'
#resolve = "wiki-lookup"
resolve = 'wiki-pickle'

[[assets]]
name = 'linker'
resolve = 'wikidata-elastic'
#resolve = "wikidata-20200709-direct-prefLabel-en"
#resolve = "wikidata-cluster"


[[step]]
step = "load"
vals = "data/TabEL/10k-part-*"

[[step]]
step = "reshape"
restructure = true
    [[step.unpivot_heuristics]]
    class = "NumSuffix"
    
    [[step.unpivot_heuristics]]
    class = "SeqPrefix"
    
    [[step.unpivot_heuristics]]
    class = "SpannedRepeat"
    
    [[step.unpivot_heuristics]]
    class = "AgentLikeHyperlink"
    lookup_config = {resolve = "lookup"}
    kb_config = {resolve = "linker"}
    bad_types = [
        'http://www.wikidata.org/entity/Q4167410',
        'http://www.wikidata.org/entity/Q13406463',
        'http://www.wikidata.org/entity/Q47574',
    ]
    bad_props = [
        'http://www.wikidata.org/prop/direct/P1687',
    ]

[[step]]
step = "link"
lookup_cells = true
lookup_config = {resolve = "lookup"}
linker_config = {}

[[step]]
step = "coltypes"
    [step.typer_config]
    class = "EntityType"
    db = {resolve = "linker"}
    type_prop = "http://www.wikidata.org/prop/direct/P31"
    supertype_prop = '' #"http://www.wikidata.org/prop/direct/P279"
    cover_threshold = 0.333

#[[step]]
#step = "cluster"
#addcontext = ["pgTitle"]
#headerunions = true