name = "TabEL"
datadir = "data"

[[assets]]
name  = "tabel"
class = "Annotation"
download = [
    "http://websail-fe.cs.northwestern.edu/TabEL/tables.json.gz",
]
path = "data/TabEL"
fname = "tables.json.gz"


[[step]]
step = "load"
vals = "data/TabEL/10k-part-*"

[[step]]
step = "reshape"
restructure = true
    [[step.unpivot_heuristics]]
    class = "NumSuffix"
    
    [[step.unpivot_heuristics]]
    class = "SeqPrefix"
    
    [[step.unpivot_heuristics]]
    class = "SpannedRepeat"
    
    [[step.unpivot_heuristics]]
    class = "AgentLikeHyperlink"
    lookup_config = {name = 'wiki-lookup'}
    kb_config = {name = "wikidata-cluster"}
    bad_types = [
        'http://www.wikidata.org/entity/Q4167410',
        'http://www.wikidata.org/entity/Q13406463',
        'http://www.wikidata.org/entity/Q47574',
    ]
    bad_props = [
        'http://www.wikidata.org/prop/direct/P1687',
    ]

[[step]]
step = "link"
lookup_config = {name = 'wiki-lookup'}
linker_config = {}

[[step]]
step = "cluster"
addcontext = ["pgTitle"]
headerunions = true