name = 'TabEL'


[[assets]]
name  = 'tabel'
class = 'Annotation'
download = [
    'http://websail-fe.cs.northwestern.edu/TabEL/tables.json.gz',
]
path = 'data/TabEL'
fname = 'tables.json.gz'

[[assets]]
name = 'lookup'
resolve = 'wdid-sqlite'
sqlitedb = 'data/wdid_wpname.sqlitedb'
#fallback = {class = 'MediaWikiAPI'}

[[assets]]
name = 'linker'
resolve = 'wikidata-trident'


## Pipeline ##

[inputs]
# path = '/bigstore/kruit/tabel/split-parts/*'
path = 'hdfs://bricks07:9000/user/kruit/tabel/*'
# executor = {class = 'DaskHashBag', address = 'tcp://192.168.62.207:8786'}

[[step]]
step = 'reshape'
restructure = true
prefix_header_rules = [{find='Precededby ', header='Preceded by'}, {find='Succeededby ', header='Succeeded by'}, {find='Previousrace:', header='Previous race'}, {find='Nextrace:', header='Next race'}]
# compound_splitter = {class = "reshape.SpacyCompoundSplitter"}
discard_headerless_tables = true

    [[step.unpivot_heuristics]]
    class = 'reshape.NumSuffix'
    min_len = 2

    [[step.unpivot_heuristics]]
    name = 'year-prefix'
    class = 'reshape.RegexFinder'
    find_regex = '[\W\s]*[0-9]{4}.*'
    split_regex = '(?P<cell>[\d\W]{4})[\W\s]*(?P<head>.*?)[\W\s]*$'

    [[step.unpivot_heuristics]]
    name = 'year-suffix'
    class = 'reshape.RegexFinder'
    find_regex = '.*[0-9]{4}[\W\s]*$'
    split_regex = '(?P<head>.*?)[\W\s]*(?P<cell>[0-9]{4}?)[\W\s]*$'
    
    [[step.unpivot_heuristics]]
    name = 'short-uppercase-acronyms'
    class = 'reshape.RegexFinder'
    find_regex = '[A-Z]{2,4}$'
    min_len = 3

    [[step.unpivot_heuristics]]
    name = 'time'
    class = 'reshape.RegexFinder'
    find_regex = '.*\d{1,2}:\d{2} ?[AP]M.*'
    split_regex = '(?P<head>.*?)[\W\s]*(?P<cell>\d{1,2}:\d{2}[AP]M).*'

    [[step.unpivot_heuristics]]
    class = 'reshape.SpannedRepeat'
    
    [[step.unpivot_heuristics]]
    class = 'reshape.AgentLikeHyperlink'
    lookup = {resolve = 'lookup', extract='http://en.wikipedia.org/wiki/([^?]+)\?'}
    kb = {resolve = 'linker'}
    bad_types = [
        'http://www.wikidata.org/entity/Q4167410',
        'http://www.wikidata.org/entity/Q13406463',
        'http://www.wikidata.org/entity/Q47574',
    ]
    bad_props = [
        'http://www.wikidata.org/prop/direct/P1687',
    ]

    [[step.unpivot_heuristics]]
    class = 'reshape.AttributeContext'
    attname = 'pgTitle'

    [[step.unpivot_heuristics]]
    class = 'reshape.Rule'
    name = 'poll'
    id_vars = ["Poll source", "Date(s) administered", "Sample size", "Margin of error"]

    [[step.unpivot_heuristics]]
    class = 'reshape.Rule'
    name = 'baseball'
    value_vars = ['1', '2', '3', '4', '5', '6', '7', '8', '9', 'R', 'H', 'E']


    [[step.unpivot_heuristics]]
    class = 'reshape.Rule'
    name = 'train'
    id_vars = ["Preceding station", "Following station"]
    
    


[[step]]
step = 'cluster'
addcontext = ['pgTitle']
headerunions = true


[[step]]
step = 'filter'
filters = ['table["numDataRows"] > 10', 'table.get("numTables", 1) > 1']

[[step]]
step = 'link'
lookup_cells = true
lookup = {resolve = 'wdid-sqlite'}

    
[[step]]
step = 'coltypes'
    [step.typer]
    class = 'link.EntityTyper'
    db = {resolve = 'linker'}
    type_prop = 'http://www.wikidata.org/prop/direct/P31'
    supertype_prop = 'http://www.wikidata.org/prop/direct/P279'
    cover_threshold = 0.333

[[step]]
step = 'cluster'
addcontext = []
headerunions = false
agg_func = '@mean(  @max(headjacc, @pow(headvec, 4)), @max(bodylsh, @pow(bodyvec, 4), bodytype ) )'
agg_threshold = 0.98
#align_columns = 'max1' # much faster than 'greedy' but it sucks
edge_exp = 6
agg_threshold_col = 0.1
keep_partition_meta = ['_id', 'tableHeaders', 'tableData', 'entities', 'classes']
mergeheaders_topn = 1
max_cluster_size = 250

    [[step.filters]]
    name  = 'section'
    class = 'cluster.matchers.CellJaccMatcher'
    source='sectionTitle'

    [[step.filters]]
    name  = 'headjacc' # use headjacc as both matcher and filter
    class = 'cluster.matchers.CellJaccMatcher'
    source = 'head'

    
    [[step.matchers]]
    name  = 'headjacc' # use headjacc as both matcher and filter
    class = 'cluster.matchers.CellJaccMatcher'
    source = 'head'
    
    [[step.matchers]]
    name  = 'headvec'
    class = 'cluster.matchers.EmbeddingMatcher'
    source = 'head'
    wordvec_fname = './data/glove.6B.50d.pickle'
    threshold = 0.5

    [[step.matchers]]
    name  = 'bodylsh'
    class = 'cluster.matchers.LSHMatcher'
    source = 'body'
    threshold = 0.5
    
    [[step.matchers]]
    name  = 'bodyvec'
    class = 'cluster.matchers.EmbeddingMatcher'
    source = 'body'
    wordvec_fname = './data/glove.6B.50d.pickle'
    threshold = 0.5
    
    [[step.matchers]]
    name  = 'bodytype'
    class = 'cluster.matchers.TypeCosMatcher'

[[step]]
step = 'link'
lookup_cells = true
lookup = {resolve = 'wdid-sqlite'}

[[step]]
step = 'coltypes'
    [step.typer]
    class = 'link.EntityTyper'
    db = {resolve = 'linker'}
    type_prop = 'http://www.wikidata.org/prop/direct/P31'
    supertype_prop = ''
    cover_threshold = 0.333

[[step]]
step = 'integrate'
pfd_threshold = 0.95
db = {resolve = 'linker'}

[[step]]
step = 'triples'
