name = "TabEL"
datadir = "data"

[[assets]]
name  = "tabel"
class = "Annotation"
download = [
    "http://websail-fe.cs.northwestern.edu/TabEL/tables.json.gz",
]
path = "data/TabEL"
fname = "tables.json.gz"

[[assets]]
name = 'lookup'
#resolve = 'wikidata-elastic'
resolve = "wiki-sqlite"
#sqlitedb = 'data/wdid_wpname.sqlitedb'
sqlitedb = "/export/scratch1/home/kruit/data/wdid_wpname.sqlitedb"
#fallback = {class = 'MediaWikiAPI'}

[[assets]]
name = 'linker'
#resolve = 'wikidata-elastic'
#resolve = "wikidata-20200709-direct-prefLabel-en"
#resolve = "wikidata-cluster"
#resolve = 'wikidata-cache'
#sqlitedb = 'data/wikidata-cache.sqlitedb'
#fallback = {resolve = "wikidata-20200709-direct-prefLabel-en"}
class = "RDFSearcher"
typeProperties = ["http://www.wikidata.org/prop/direct/P31"]
    [assets.store]
    class = "Trident"
    configuration = "/export/scratch1/home/kruit/20200713-prop-skos"


[[step]]
step = "load"
vals = "data/TabEL/10k-part-*"

[[step]]
step = "reshape"
restructure = true
    [[step.unpivot_heuristics]]
    class = "NumSuffix"
    
    [[step.unpivot_heuristics]]
    class = "SeqPrefix"
    
    [[step.unpivot_heuristics]]
    class = "SpannedRepeat"
    
    [[step.unpivot_heuristics]]
    class = "AgentLikeHyperlink"
    lookup_config = {resolve = "lookup"}
    kb_config = {resolve = "wikidata-cache"}
    bad_types = [
        'http://www.wikidata.org/entity/Q4167410',
        'http://www.wikidata.org/entity/Q13406463',
        'http://www.wikidata.org/entity/Q47574',
    ]
    bad_props = [
        'http://www.wikidata.org/prop/direct/P1687',
    ]

[[step]]
step = "link"
lookup_cells = false
lookup_config = {resolve = "lookup"}
linker_config = {}

[[step]]
step = "coltypes"
    [step.typer_config]
    class = "EntityType"
    db = {resolve = "linker"}
    type_prop = "http://www.wikidata.org/prop/direct/P31"
    supertype_prop = '' #"http://www.wikidata.org/prop/direct/P279"
    cover_threshold = 0.333

[[step]]
step = "cluster"
addcontext = ["pgTitle"]
headerunions = true