name = "TabEL"


[[assets]]
name  = "tabel"
class = "Annotation"
download = [
    "http://websail-fe.cs.northwestern.edu/TabEL/tables.json.gz",
]
path = "data/TabEL"
fname = "tables.json.gz"

[[assets]]
name = 'lookup'
resolve = "wiki-sqlite"
sqlitedb = 'data/wdid_wpname.sqlitedb'
#fallback = {class = 'MediaWikiAPI'}

[[assets]]
name = 'linker'
resolve = "wikidata-trident"


## Pipeline ##

[input_tables]
input = "load"
path = "data/TabEL/part-*"

[[step]]
step = "reshape"
restructure = true
prefix_header_rules = [{find='Precededby ',header='Preceded by'}, {find='Succeededby ',header='Succeeded by'}]
split_compound_columns = true

    [[step.unpivot_configs]]
    class = "NumSuffix"
    
    [[step.unpivot_configs]]
    class = "SeqPrefix"
    
    [[step.unpivot_configs]]
    class = "SpannedRepeat"
    
    [[step.unpivot_configs]]
    class = "AgentLikeHyperlink"
    lookup = {resolve = "lookup"}
    kb = {resolve = "linker"}
    bad_types = [
        'http://www.wikidata.org/entity/Q4167410',
        'http://www.wikidata.org/entity/Q13406463',
        'http://www.wikidata.org/entity/Q47574',
    ]
    bad_props = [
        'http://www.wikidata.org/prop/direct/P1687',
    ]

[[step]]
step = "cluster"
addcontext = ["pgTitle"]
headerunions = true


[[step]]
step = "link"
linker_config = {}
lookup_cells = true
lookup_config = {resolve = 'wiki-sqlite'}

    
[[step]]
step = "coltypes"
    [step.typer_config]
    class = "EntityTyper"
    db = {resolve = "linker"}
    type_prop = "http://www.wikidata.org/prop/direct/P31"
    supertype_prop = "http://www.wikidata.org/prop/direct/P279"
    cover_threshold = 0.333

[[step]]
step = "cluster"
addcontext = []
headerunions = false
agg_func = '@mean(  @max(headjacc, @pow(headvec, 4)), @max(bodylsh, @pow(bodyvec, 4), bodytype ) )'
agg_threshold = 0.9
edge_exp = 6
agg_threshold_col = 0.5
store_align_meta = ["_id", "tableHeaders", "tableData", "entities", "classes"]
mergeheaders_topn = 1
    
    [[step.matcher_configs]]
    name  = 'headjacc'
    class = 'CellJaccMatcher'
    source = 'head'
    tokenize = true
    
    [[step.matcher_configs]]
    name  = 'headvec'
    class = 'EmbeddingMatcher'
    source = 'head'
    wordvec_fname = "./data/glove.6B.50d.pickle"
    threshold = 0.5

    [[step.matcher_configs]]
    name  = 'bodylsh'
    class = 'LSHMatcher'
    source = 'body'
    threshold = 0.5
    
    [[step.matcher_configs]]
    name  = 'bodyvec'
    class = 'EmbeddingMatcher'
    source = 'body'
    wordvec_fname = "./data/glove.6B.50d.pickle"
    threshold = 0.5
    
    [[step.matcher_configs]]
    name  = 'bodytype'
    class = 'TypeCosMatcher'

[[step]]
step = "link"
linker_config = {}
lookup_cells = true
lookup_config = {resolve = 'wiki-sqlite'}

[[step]]
step = "integrate"
pfd_threshold = 0.95
db_config = {resolve = "linker"}
    [step.typer_config]
    class = "EntityTyper"
    db = {resolve = "linker"}
    type_prop = "http://www.wikidata.org/prop/direct/P31"
    supertype_prop = ""
    cover_threshold = 0.333

[[step]]
step = "triples"