name = "TabEL"
datadir = "data"

[[assets]]
name  = "tabel"
class = "Annotation"
download = [
    "http://websail-fe.cs.northwestern.edu/TabEL/tables.json.gz",
]
path = "data/TabEL"
fname = "tables.json.gz"

[[assets]]
name = 'lookup'
resolve = "wiki-sqlite"
sqlitedb = 'data/wdid_wpname.sqlitedb'
#fallback = {class = 'MediaWikiAPI'}

[[assets]]
name = 'linker'
resolve = "wikidata-trident"

[[step]]
step = "load"
vals = "data/TabEL/10k-part-*"

[[step]]
step = "reshape"
restructure = true
    [[step.unpivot_configs]]
    class = "NumSuffix"
    
    [[step.unpivot_configs]]
    class = "SeqPrefix"
    
    [[step.unpivot_configs]]
    class = "SpannedRepeat"
    
    [[step.unpivot_configs]]
    class = "AgentLikeHyperlink"
    lookup = {resolve = "lookup"}
    kb = {resolve = "wikidata-cache"}
    bad_types = [
        'http://www.wikidata.org/entity/Q4167410',
        'http://www.wikidata.org/entity/Q13406463',
        'http://www.wikidata.org/entity/Q47574',
    ]
    bad_props = [
        'http://www.wikidata.org/prop/direct/P1687',
    ]

[[step]]
step = "cluster"
addcontext = ["pgTitle"]
headerunions = true

[[step]]
step = "link"
lookup_cells = true
lookup_config = {resolve = "lookup"}
linker_config = {}

[[step]]
step = "coltypes"
    [step.typer_config]
    class = "EntityTyper"
    db = {resolve = "linker"}
    type_prop = "http://www.wikidata.org/prop/direct/P31"
    supertype_prop = '' #"http://www.wikidata.org/prop/direct/P279"
    cover_threshold = 0.2

[[step]]
step = "integrate"
pfd_threshold = 0.95
db_config = {resolve = "linker"}
