name = "TabEL"
datadir = "data"

[[assets]]
name  = "tabel"
class = "Annotation"
download = [
    "http://websail-fe.cs.northwestern.edu/TabEL/tables.json.gz",
]
path = "data/TabEL"
fname = "tables.json.gz"


[[step]]
step = "load"
vals = "data/TabEL/part-*"

[[step]]
step = "reshape"
split_compound_columns = false
heuristics = [{class = "NumSuffix"}]

[[step]]
step = "cluster"
addcontext = ["pgTitle"]
headerunions = true