[[assets]]
name = 'lookup'
resolve = 'wiki-sqlite'

[[assets]]
name = 'linker'
resolve = 'wikidata-trident'

[input_tables]
input = 'extract'
    [input_tables.source]
    class = 'WarcPages'
    globstrings = ['./data/wikipedia-2019-12-P2291/*-00000.warc.gz']

